### PR TITLE
Implement xdelta3 and fix lua env replacement 

### PR DESCRIPTION
**Pull request by manuelsteiner**
This implements xdelta3 instead of xdelta. The two versions are
incompatible. While some Linux distributions, such as Debian,
provide xdelta and xdelta3 where both work according to their
version, other distributions, such as Fedora, only provide the
functionality of xdelta3 and symlink xdelta to xdelta3. This means
that syncmaildir can not run on those distributions. By switching
to xdelta3, most modern distributions should be supported.
The syntax on how to generate a delta file as well as how to apply
one is different in xdelta3 as well. This has been accounted for in
the change.

Replacing the lua env shebang in the Makefile was only working for
some of the lua files included in the project. This has been unified
to work for all lua files by altering the Makefile as well as the
two lua files smd-server and smd-client. The shebang now does not
contain a space after it (#!/usr/bin/env). That is arguably the
most common implementation, so the change accounts for that in the
Makefile too.

### CODE REVIEW

**Comment by gares** [comment]
Many thanks! I've just added to master CI support. Would you mind rebasing on top of master so that CI runs on this PR (you'd also need to fix https://github.com/gares/syncmaildir/blob/master/.github/workflows/main.yml to install xdelta3 instead of xdelta in the PR)?

Alternatively I can do it for you if you prefer (I don't know if you are familiar with git's gimmicks)

**Comment by manuelsteiner** [comment]
Sure, will do. Might take me a day or two until I get to it though.

**Comment by manuelsteiner** [comment]
Hm, does Github actions not like a different main.yml file? I never used actions so I have no clue.

**Comment by gares** [comment]
You must have done something wrong playing git :-/
Can I push to your branch?

**Comment by manuelsteiner** [comment]
Sure feel free. I thought rebasing on top of your master is enough. Granted I forgot to pull the one change adding a space somewhere. Maybe that created an issue.

Can you do that as is or do I need to somehow allow you to do so?

**Comment by manuelsteiner** [comment]
Alright... I think I figured it out.

**Comment by gares** [comment]
Great, it passes CI

**Pull request merged**
